### ISSUE TITLE
Customise switch_data name

### ISSUE THREAD

**Issue by juliettelimozin** [CAM-Roche/RandomisedTrialsEmulation#47]
Hi @gravesti , is it possible to add a clause in initiators() that allows us to customise the file name of "switch_data.csv"? Having it defaulted to this name makes parallelised simulations using this function difficult because there's only one switch_data.csv for multiple parallel jobs requiring their own switch_data.csv. Thanks!

**Comment by gravesti** [comment]
Hi @juliettelimozin, yes I can look at this, but i wonder if it is already possible using the `data_dir` argument to `initiators()`. You would give each simulation it's own folder. Otherwise I'm worried that the other temporary files will be colliding if all the simulations are running in the same place.

**Comment by gravesti** [comment]
Yes, exactly. In your iterations you could do something like

```r
for (s in 1:10) {
  sim_dir <- paste0("my_dir/simulations/s_", s)
  if (dir.exists(sim_dir)) unlink(sim_dir, recursive = TRUE) # delete directory if it exists, to remove old results
  dir.create(sim_dir)
 # ...
  initiators( ..., data_dir = sim_dir)
 # ...
}
```
